try:
    from _udask_cffi import ffi, lib
except ImportError:
    ffi = None
    lib = None
    pass


dask_errors = {
    '_': {},
    'Generic': {'No Error': 0, 'Unknown Card Type': -1, 'Invalid Card Number': -2,
                'Too Many Card Registered': -3, 'Card Not Registered': -4, 'Func Not Support': -5,
                'Invalid IO Channel': -6, 'Invalid Ad Range': -7, 'Cont IO Not Allowed': -8,
                'Diff Range Not Support': -9, 'Last Channel Not Zero': -10,
                'Channel Not Descending': -11, 'Channel Not Ascending': -12,
                'Open Driver Failed': -13, 'Open Event Failed': -14, 'Transfer Count Too Large': -15,
                'Not Double Buffer Mode': -16, 'Invalid Sample Rate': -17, 'Invalid Counter Mode': -18,
                'Invalid Counter': -19, 'Invalid Counter State': -20, 'Invalid Bin Bcd Param': -21,
                'Bad Card Type': -22, 'Invalid Da Ref Voltage': -23, 'Ad Time Out': -24,
                'No Async AI': -25, 'No Async AO': -26, 'No Async DI': -27, 'No Async DO': -28,
                'Not Input Port': -29, 'Not Output Port': -30, 'Invalid DIO Port': -31,
                'Invalid DIO Line': -32, 'Cont IO Active': -33, 'Dbl Buf Mode Not Allowed': -34,
                'Config Failed': -35, 'Invalid Port Direction': -36, 'Begin Thread Error': -37,
                'Invalid Port Width': -38, 'Invalid Ctr Source': -39, 'Open File': -40,
                'Allocate Memory': -41, 'Da Voltage Out Of Range': -42, 'Lock Memory': -43,
                'DIO Data Width Error': -44, 'Task Code Error': -45, 'Trigger Count Error': -46,
                'Invalid Trigger Mode': -47, 'Invalid Trigger Type': -48, 'Invalid Counter Value': -50,
                'Invalid Event Handle': -60, 'No Message Available': -61, 'Event Message Not Added': -62,
                'Calibration Time Out': -63, 'Undefined Parameter': -64, 'Invalid Buffer ID': -65,
                'Invalid Sampled Clock': -66, 'Invalid Operation Mode': -67},
    'Driver API': {'Config Ioctl': -201, 'Async Set Ioctl': -202, 'DB Set Ioctl': -203,
                   'DB Half Ready Ioctl': -204, 'Cont OP Ioctl': -205, 'Cont Status Ioctl': -206,
                   'PIO Ioctl': -207, 'D Int Set Ioctl': -208, 'Wait Evt Ioctl': -209, 'Open Evt Ioctl': -210,
                   'COS Int Set Ioctl': -211, 'Mem Map Ioctl': -212, 'Mem U Map Set Ioctl': -213,
                   'CTR Ioctl': -214, 'Get Res Ioctl': -215, 'Cal Ioctl': -216, 'PM Int Set Ioctl': -217},
    'Jeff': {'Access Violation Data Copy': -301, 'No Module Found': -302, 'Card ID Duplicated': -303,
             'Card Disconnected': -304, 'Invalid Scanned Index': -305, 'Undefined Exception': -306,
             'Invalid DIO Config': -307, 'Invalid AO Cfg Ctrl': -308, 'Invalid AO Trig Ctrl': -309,
             'Conflict With Sync Mode': -310, 'Conflict With Fifo Mode': -311, 'Invalid AO Iteration': -312,
             'Zero Channel Number': -313, 'System Call Failed': -314, 'Timeout From Sync Mode': -315,
             'Invalid Pulse Count': -316, 'Invalid Delay Count': -317, 'Conflict With Delay': -318,
             'AO Fifo Count Too Large': -319, 'Conflict With Wave Repeat': -320, 'Conflict With Re Trig': -321,
             'Invalid Trigger Channel': -322, 'Invalid Input Signal': -323, 'Invalid Conversion Src': -324,
             'Invalid Ref Voltage': -325, 'Calibrate Failed': -326, 'Invalid Cal Data': -327,
             'Chan Gain Queue Too Large': -328, 'Invalid Card Type': -329, 'Invalid Sync Mode': -330,
             'IIC Version': -331, 'F Upgrade Failed': -332, 'Invalid Read Count': -333,
             'TEDS Invalid Sensor No': -334, 'TEDS Access Timeout': -335, 'TEDS Checksum Failed': -336,
             'TEDS Not IEE': -337, 'TEDS Invalid Template ID': -338, 'TEDS Invalid Precision Value': -339,
             'TEDS Unsupported Template': -340, 'TEDS Invalid Property ID': -341, 'TEDS No Raw Data': -342,
             'Invalid Channel': -397, 'Null Point': -398, 'Invalid Param Setting': -399},
    'Kernel': {'AI Start Failed': -401, 'AO Start Failed': -402, 'Conflict With GPIO Config': -403,
               'EEPROM Readback': -404, 'Conflict With Infinite Op': -405, 'Waiting USB Host Response': -406,
               'AO Fifo Mode Timeout': -407, 'Invalid Module Function': -408, 'Ad Fifo Full': -409,
               'Invalid Transfer Count': -410, 'Conflict With AI Config': -411, 'DDS Config Failed': -412,
               'FPGA Access Failed': -413, 'PLD Busy': -414, 'PLD Timeout': -415, 'Undefined Kernel Error': -420},
    'Future': {'Sync Mode Not Support': -501}}

dask_errors_reverse = {
    0: {'category': 'Generic', 'description': 'No Error'},
    -1: {'category': 'Generic', 'description': 'Unknown Card Type'},
    -2: {'category': 'Generic', 'description': 'Invalid Card Number'},
    -3: {'category': 'Generic', 'description': 'Too Many Card Registered'},
    -4: {'category': 'Generic', 'description': 'Card Not Registered'},
    -5: {'category': 'Generic', 'description': 'Func Not Support'},
    -6: {'category': 'Generic', 'description': 'Invalid IO Channel'},
    -7: {'category': 'Generic', 'description': 'Invalid Ad Range'},
    -8: {'category': 'Generic', 'description': 'Cont IO Not Allowed'},
    -9: {'category': 'Generic', 'description': 'Diff Range Not Support'},
    -10: {'category': 'Generic', 'description': 'Last Channel Not Zero'},
    -11: {'category': 'Generic', 'description': 'Channel Not Descending'},
    -12: {'category': 'Generic', 'description': 'Channel Not Ascending'},
    -13: {'category': 'Generic', 'description': 'Open Driver Failed'},
    -14: {'category': 'Generic', 'description': 'Open Event Failed'},
    -15: {'category': 'Generic', 'description': 'Transfer Count Too Large'},
    -16: {'category': 'Generic', 'description': 'Not Double Buffer Mode'},
    -17: {'category': 'Generic', 'description': 'Invalid Sample Rate'},
    -18: {'category': 'Generic', 'description': 'Invalid Counter Mode'},
    -19: {'category': 'Generic', 'description': 'Invalid Counter'},
    -20: {'category': 'Generic', 'description': 'Invalid Counter State'},
    -21: {'category': 'Generic', 'description': 'Invalid Bin Bcd Param'},
    -22: {'category': 'Generic', 'description': 'Bad Card Type'},
    -23: {'category': 'Generic', 'description': 'Invalid Da Ref Voltage'},
    -24: {'category': 'Generic', 'description': 'Ad Time Out'},
    -25: {'category': 'Generic', 'description': 'No Async AI'},
    -26: {'category': 'Generic', 'description': 'No Async AO'},
    -27: {'category': 'Generic', 'description': 'No Async DI'},
    -28: {'category': 'Generic', 'description': 'No Async DO'},
    -29: {'category': 'Generic', 'description': 'Not Input Port'},
    -30: {'category': 'Generic', 'description': 'Not Output Port'},
    -31: {'category': 'Generic', 'description': 'Invalid DIO Port'},
    -32: {'category': 'Generic', 'description': 'Invalid DIO Line'},
    -33: {'category': 'Generic', 'description': 'Cont IO Active'},
    -34: {'category': 'Generic', 'description': 'Dbl Buf Mode Not Allowed'},
    -35: {'category': 'Generic', 'description': 'Config Failed'},
    -36: {'category': 'Generic', 'description': 'Invalid Port Direction'},
    -37: {'category': 'Generic', 'description': 'Begin Thread Error'},
    -38: {'category': 'Generic', 'description': 'Invalid Port Width'},
    -39: {'category': 'Generic', 'description': 'Invalid Ctr Source'},
    -40: {'category': 'Generic', 'description': 'Open File'},
    -41: {'category': 'Generic', 'description': 'Allocate Memory'},
    -42: {'category': 'Generic', 'description': 'Da Voltage Out Of Range'},
    -43: {'category': 'Generic', 'description': 'Lock Memory'},
    -44: {'category': 'Generic', 'description': 'DIO Data Width Error'},
    -45: {'category': 'Generic', 'description': 'Task Code Error'},
    -46: {'category': 'Generic', 'description': 'Trigger Count Error'},
    -47: {'category': 'Generic', 'description': 'Invalid Trigger Mode'},
    -48: {'category': 'Generic', 'description': 'Invalid Trigger Type'},
    -50: {'category': 'Generic', 'description': 'Invalid Counter Value'},
    -60: {'category': 'Generic', 'description': 'Invalid Event Handle'},
    -61: {'category': 'Generic', 'description': 'No Message Available'},
    -62: {'category': 'Generic', 'description': 'Event Message Not Added'},
    -63: {'category': 'Generic', 'description': 'Calibration Time Out'},
    -64: {'category': 'Generic', 'description': 'Undefined Parameter'},
    -65: {'category': 'Generic', 'description': 'Invalid Buffer ID'},
    -66: {'category': 'Generic', 'description': 'Invalid Sampled Clock'},
    -67: {'category': 'Generic', 'description': 'Invalid Operation Mode'},
    -201: {'category': 'Driver API', 'description': 'Config Ioctl'},
    -202: {'category': 'Driver API', 'description': 'Async Set Ioctl'},
    -203: {'category': 'Driver API', 'description': 'DB Set Ioctl'},
    -204: {'category': 'Driver API', 'description': 'DB Half Ready Ioctl'},
    -205: {'category': 'Driver API', 'description': 'Cont OP Ioctl'},
    -206: {'category': 'Driver API', 'description': 'Cont Status Ioctl'},
    -207: {'category': 'Driver API', 'description': 'PIO Ioctl'},
    -208: {'category': 'Driver API', 'description': 'D Int Set Ioctl'},
    -209: {'category': 'Driver API', 'description': 'Wait Evt Ioctl'},
    -210: {'category': 'Driver API', 'description': 'Open Evt Ioctl'},
    -211: {'category': 'Driver API', 'description': 'COS Int Set Ioctl'},
    -212: {'category': 'Driver API', 'description': 'Mem Map Ioctl'},
    -213: {'category': 'Driver API', 'description': 'Mem U Map Set Ioctl'},
    -214: {'category': 'Driver API', 'description': 'CTR Ioctl'},
    -215: {'category': 'Driver API', 'description': 'Get Res Ioctl'},
    -216: {'category': 'Driver API', 'description': 'Cal Ioctl'},
    -217: {'category': 'Driver API', 'description': 'PM Int Set Ioctl'},
    -301: {'category': 'Jeff', 'description': 'Access Violation Data Copy'},
    -302: {'category': 'Jeff', 'description': 'No Module Found'},
    -303: {'category': 'Jeff', 'description': 'Card ID Duplicated'},
    -304: {'category': 'Jeff', 'description': 'Card Disconnected'},
    -305: {'category': 'Jeff', 'description': 'Invalid Scanned Index'},
    -306: {'category': 'Jeff', 'description': 'Undefined Exception'},
    -307: {'category': 'Jeff', 'description': 'Invalid DIO Config'},
    -308: {'category': 'Jeff', 'description': 'Invalid AO Cfg Ctrl'},
    -309: {'category': 'Jeff', 'description': 'Invalid AO Trig Ctrl'},
    -310: {'category': 'Jeff', 'description': 'Conflict With Sync Mode'},
    -311: {'category': 'Jeff', 'description': 'Conflict With Fifo Mode'},
    -312: {'category': 'Jeff', 'description': 'Invalid AO Iteration'},
    -313: {'category': 'Jeff', 'description': 'Zero Channel Number'},
    -314: {'category': 'Jeff', 'description': 'System Call Failed'},
    -315: {'category': 'Jeff', 'description': 'Timeout From Sync Mode'},
    -316: {'category': 'Jeff', 'description': 'Invalid Pulse Count'},
    -317: {'category': 'Jeff', 'description': 'Invalid Delay Count'},
    -318: {'category': 'Jeff', 'description': 'Conflict With Delay'},
    -319: {'category': 'Jeff', 'description': 'AO Fifo Count Too Large'},
    -320: {'category': 'Jeff', 'description': 'Conflict With Wave Repeat'},
    -321: {'category': 'Jeff', 'description': 'Conflict With Re Trig'},
    -322: {'category': 'Jeff', 'description': 'Invalid Trigger Channel'},
    -323: {'category': 'Jeff', 'description': 'Invalid Input Signal'},
    -324: {'category': 'Jeff', 'description': 'Invalid Conversion Src'},
    -325: {'category': 'Jeff', 'description': 'Invalid Ref Voltage'},
    -326: {'category': 'Jeff', 'description': 'Calibrate Failed'},
    -327: {'category': 'Jeff', 'description': 'Invalid Cal Data'},
    -328: {'category': 'Jeff', 'description': 'Chan Gain Queue Too Large'},
    -329: {'category': 'Jeff', 'description': 'Invalid Card Type'},
    -330: {'category': 'Jeff', 'description': 'Invalid Sync Mode'},
    -331: {'category': 'Jeff', 'description': 'IIC Version'},
    -332: {'category': 'Jeff', 'description': 'F Upgrade Failed'},
    -333: {'category': 'Jeff', 'description': 'Invalid Read Count'},
    -334: {'category': 'Jeff', 'description': 'TEDS Invalid Sensor No'},
    -335: {'category': 'Jeff', 'description': 'TEDS Access Timeout'},
    -336: {'category': 'Jeff', 'description': 'TEDS Checksum Failed'},
    -337: {'category': 'Jeff', 'description': 'TEDS Not IEE'},
    -338: {'category': 'Jeff', 'description': 'TEDS Invalid Template ID'},
    -339: {'category': 'Jeff', 'description': 'TEDS Invalid Precision Value'},
    -340: {'category': 'Jeff', 'description': 'TEDS Unsupported Template'},
    -341: {'category': 'Jeff', 'description': 'TEDS Invalid Property ID'},
    -342: {'category': 'Jeff', 'description': 'TEDS No Raw Data'},
    -397: {'category': 'Jeff', 'description': 'Invalid Channel'},
    -398: {'category': 'Jeff', 'description': 'Null Point'},
    -399: {'category': 'Jeff', 'description': 'Invalid Param Setting'},
    -401: {'category': 'Kernel', 'description': 'AI Start Failed'},
    -402: {'category': 'Kernel', 'description': 'AO Start Failed'},
    -403: {'category': 'Kernel', 'description': 'Conflict With GPIO Config'},
    -404: {'category': 'Kernel', 'description': 'EEPROM Readback'},
    -405: {'category': 'Kernel', 'description': 'Conflict With Infinite Op'},
    -406: {'category': 'Kernel', 'description': 'Waiting USB Host Response'},
    -407: {'category': 'Kernel', 'description': 'AO Fifo Mode Timeout'},
    -408: {'category': 'Kernel', 'description': 'Invalid Module Function'},
    -409: {'category': 'Kernel', 'description': 'Ad Fifo Full'},
    -410: {'category': 'Kernel', 'description': 'Invalid Transfer Count'},
    -411: {'category': 'Kernel', 'description': 'Conflict With AI Config'},
    -412: {'category': 'Kernel', 'description': 'DDS Config Failed'},
    -413: {'category': 'Kernel', 'description': 'FPGA Access Failed'},
    -414: {'category': 'Kernel', 'description': 'PLD Busy'},
    -415: {'category': 'Kernel', 'description': 'PLD Timeout'},
    -420: {'category': 'Kernel', 'description': 'Undefined Kernel Error'},
    -501: {'category': 'Future', 'description': 'Sync Mode Not Support'}}


def check_error(error_code):
    if error_code in dask_errors_reverse:
        return dask_errors_reverse[error_code]
    return {'category': None, 'description': None}
